shared:
    image: golang
    environment:
        GOPATH: /sd/workspace
        GO111MODULE: on

jobs:
    main:
        environment:
            SD_SONAR_OPTS:  "-Dsonar.sources=./ -Dsonar.exclusions=**/*_test.go,**/vendor/** -Dsonar.tests=./ -Dsonar.test.inclusions=**/*_test.go -Dsonar.test.exclusions=**/vendor/** -Dsonar.go.coverage.reportPaths=${SD_ARTIFACTS_DIR}/coverage.out -Dsonar.go.tests.reportPaths=${SD_ARTIFACTS_DIR}/report.json"
        requires: [~commit, ~pr]
        steps:
            - modverify: go version; go mod verify
            - gofmt: |
                gofmtOutput=$(gofmt -l .)
                if [ -z "${gofmtOutput}" ]; then
                    echo "OK"
                else
                    echo "gofmt violations in the following file(s):"
                    echo "${gofmtOutput}\n"
                    gofmt -d .
                    exit 1
                fi
            - vet: go vet ./...
            - build: go install -v ./...
            - test: gotestsum --format testname --jsonfile ${SD_ARTIFACTS_DIR}/report.json -- -coverprofile=${SD_ARTIFACTS_DIR}/coverage.out ./...

    deploy:
        requires: main
        steps:
            - setup-ci: git clone https://github.com/screwdriver-cd/toolbox.git ci
            - build: go install -v ./...
            - tag: ./ci/git-tag.sh
            - release: |
                curl -sL https://git.io/goreleaser | bash
        secrets:
            # Pushing tags to Git
            - GIT_KEY
            # Pushing releases to GitHub
            - GITHUB_TOKEN
